export const userNotFound = 'no user found with the provided identifier'
export const emailInUse = 'email is already in use'
export const credentialsError = 'email or password invalid'
export const invalidToken = 'invalid token, unauthorized'
export const requiredToken = 'token is required'
export const unauthorized = 'unauthorized'
